image:
  repository: tccr.io/truecharts/pbs
  tag: v2.2-7@sha256:e949feab45f7e66326c292ff8e2d6f095b1465e82724705b2b6eb122a5285240
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 8007
        protocol: https
        port: 8007

persistence:
  config:
    enabled: true
    mountPath: /etc/proxmox-backup
  lib:
    enabled: true
    mountPath: /var/lib/proxmox-backup
  log:
    enabled: true
    mountPath: /var/log/proxmox-backup
  run:
    enabled: true
    type: emptyDir
    mountPath: /run
  tmp:
    enabled: true
    type: emptyDir
    mountPath: /tmp
    

portal:
  open:
    enabled: true
