image:
  repository: tccr.io/truecharts/proxmox-backup-server
  tag: v3.0.2@sha256:31e31c6bc27ca6e682eb2819ba69bec7d20bfa928e5642123e620f9be3277d3c
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
  # pod:
  #   fsGroup: 34

service:
  main:
    ports:
      main:
        targetPort: 8007
        protocol: https
        port: 8007

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: https
            readiness:
              type: https
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /etc/proxmox-backup
  lib:
    enabled: true
    type: emptyDir
    mountPath: /var/lib/proxmox-backup
  log:
    enabled: true
    type: emptyDir
    mountPath: /var/log/proxmox-backup
  run:
    enabled: true
    type: emptyDir
    mountPath: /run

portal:
  open:
    enabled: true
